apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackergeneric
spec:
  selector:
    matchLabels:
      app: trackergeneric
  template:
    metadata:
      labels:
        app: trackergeneric
    spec:
      containers:
      - name: trackergeneric
        image: sakthisaran/tracker_generic:BUILDNUMBER
        env:
        - name: GENERICSERVICE_EMAIL_ID
          valueFrom:
            secretKeyRef:
              name: secretpasswords
              key: GENERICSERVICE_EMAIL_ID
        - name: GENERICSERVICE_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretpasswords
              key: GENERICSERVICE_EMAIL_PASSWORD

        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            secretKeyRef:
              name: secretpasswords
              key: SPRING_PROFILE

        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80


